
# The name of your website.
name: In en Uit — Ademtraining / Coaching / Persoonlijke ontwikkeling

description: Portfolio of Stijn van Cuijk, a multidisciplinary designer currently studying Industrial Product Design.

# The URL of the homepage of your site (without trailing slash). Leave this
# empty when you run Jekyll locally.
url: http://localhost:4000
baseurl: ""

collections:
  fp-collection:
    output: true
    permalink: /:permalink

##################
# BUILD SETTINGS #
##################

exclude: [vendor]
kramdown:
  input: GFM
paginate_path: "/page-:num/"
permalink: pretty
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      excerpt_separator: "<!--more-->"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post-page"
      excerpt_separator: "<!--more-->"
