
# The name of your website.
name: In en Uit — Ademtraining / NLP / Systemisch coaching

description: In en Uit — Ademtraining / NLP / Systemisch coaching

# The URL of the homepage of your site (without trailing slash). Leave this
# empty when you run Jekyll locally.
url: http://localhost:4000
baseurl: ""

collections:
  paginas:
    output: true
    permalink: /:permalink

##################
# BUILD SETTINGS #
##################

exclude: [vendor]
kramdown:
  input: GFM
paginate_path: "/page-:num/"
permalink: pretty
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "paginas"
    values:
      layout: "page"
